language: android
jdk:
    - oraclejdk8
android:
  components:
    # The BuildTools version used by NewPipe
    - tools
    - build-tools-30.0.2

    # The SDK version used to compile NewPipe
    - android-30

before_install: 
  - yes | sdkmanager "platforms;android-30"
script: ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug testDebugUnitTest

licenses:
  - '.+'
