name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
#  push:
#    branches:
#      - 'master'
#      - 'dev'
#  status

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        
      - name: set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm installs
      
      - name: check if status is succed
        run: node ./.github/actions/status.js

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
      
      #- name: comment on pull request
      #  if: github.event_name == 'pull_request'
      #  # run: node ./.github/actions/artifact-comment.js
      #  uses: peter-evans/create-or-update-comment@v1
      #  with:
      #    token: ${{ secrets.GUTHUB_ACTIONS_PR_BOT_TOKEN }} # GITHUB_TOKEN
      #    issue-number: ${{  }}
      #    body: |
      #      This is a multi-line test comment
      #      - With GitHub **Markdown**
      #      - Created by [create-or-update-comment][1]
#
#            [1]: https://github.com/peter-evans/create-or-update-comment
#          reaction-type: '+1'

      - name: Create comment linking to the artifact
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'The APK was build successfuly. You can find it here:'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
